[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.7.6"

# Description
title = "AnyBody Bench Environments"
description="Extension containing suite of environments for multi-embodiment robot learning."
readme  = "docs/README.md"
repository = "https://github.com/meenalparakh/anybody.git"
category = "robotics"
keywords = ["robotics", "rl", "learning"]

[dependencies]
"isaaclab" = {}

[[python.module]]
name = "anybody"
